version: '3'

services:
  influxdb:
    image: influxdb:1.6.2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=true
    volumes:
      - ./data/influx:/var/lib/influxdb
    user: "0"

  prometheus:
    image: prom/prometheus:v2.4.0
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./data/prom:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    user: "0"

  grafana:
    image: grafana/grafana:5.1.5
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: "0"
